version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    restart: always
    volumes:
      - /srv/elasticsearch/data1:/usr/share/elasticsearch/data1
      - /srv/elasticsearch/data2:/usr/share/elasticsearch/data2
      - /srv/elasticsearch/data3:/usr/share/elasticsearch/data3
      - ./config:/usr/share/elasticsearch/config
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
