cluster.name: "graylog"
network.host: localhost
http.host: localhost
http.port: 9200
path.data:
   - /usr/share/elasticsearch/data1
   - /usr/share/elasticsearch/data2
   - /usr/share/elasticsearch/data3

